- name: deploy
  hosts: 20.84.100.119
  remote_user: root

  tasks:
    - name: install openjdk 17
      dnf:
        name: java-17-openjdk-devel
        state: latest
    - name: copy script
      ansible.builtin.copy:
        src: /root/ops/ansible/restart_service.sh
        dest: /root/restart_service.sh
    - name: copy jar
      ansible.builtin.copy:
        src: /root/FunctionalJavaApp-1.0.0.jar
        dest: /root/FunctionalJavaApp-1.0.0.jar
    - name: deploy spring application
      ansible.builtin.shell:
        "bash ~/restart_service.sh"
    - name: setup a cronjob
      ansible.builtin.cron:
        name: "start java program"
        minute: "3,13,23"
        job: "java -jar ~/FunctionalJavaApp-1.0.0.jar"